version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=marketplace
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d marketplace'"]
      interval: 3s
      timeout: 3s
      retries: 5

  marketplace:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "alembic upgrade head && python src/app/service.py"
    ports:
      - 8080:8080
    environment:
      - EMP_POSTGRES={"host":"postgres"}
    depends_on:
      postgres:
        condition: service_started